name: Build and Deploy Outlook Add-in

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build
        run: npm run build

      # Upload images to Azure Blob Storage
      - name: Upload assets to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name m3storageaccount \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
              --source dist/assets \
              --destination assets \
              --overwrite
        env:
          AZURE_STORAGE_ACCOUNT: m3storageaccount

      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/dist"
          api_location: ""
          output_location: ""
        env:
          NODE_ENV: production

      # Validate manifest.xml
      - name: Validate manifest.xml
        run: |
          npm install -g @microsoft/teamsfx-cli
          teamsfx validate --manifest manifest.xml